package com.example.sharemind.chat.content;

import lombok.Getter;

@Getter
public enum ChatWebsocketStatus {
    COUNSELOR_CHAT_CREATE,
    COUNSELOR_CHAT_START_REQUEST,
    COUNSELOR_CHAT_START,
    COUNSELOR_CHAT_LEFT_FIVE_MINUTE,
    COUNSELOR_CHAT_TIME_OVER,
    COUNSELOR_CHAT_FINISH,

    CUSTOMER_CHAT_CREATE,
    CUSTOMER_CHAT_START_RESPONSE,
    CUSTOMER_CHAT_LEFT_FIVE_MINUTE,
    CUSTOMER_CHAT_TIME_OVER,
    CUSTOMER_CHAT_FINISH_REQUEST,
    CUSTOMER_CHAT_REVIEW,
    CUSTOMER_CHAT_FINISH
}
